#
# qmake configuration for Zephyr RTOS x86_64 systems
#

include(../common/zephyr-base.conf)

# x86_64 specific flags
QMAKE_CFLAGS_RELEASE    = -Os -m64 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow
QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO = -Os -g -m64 -mno-sse -mno-mmx -mno-sse2 -mno-3dnow

QMAKE_CXXFLAGS_RELEASE  = $$QMAKE_CFLAGS_RELEASE
QMAKE_CXXFLAGS_RELEASE_WITH_DEBUGINFO = $$QMAKE_CFLAGS_RELEASE_WITH_DEBUGINFO

load(qt_config)